# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-08 06:17
from __future__ import unicode_literals

import cdacalumini.models
import cdacalumini.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=50)),
                ('Job_title', models.CharField(max_length=50)),
                ('Posted_by', models.CharField(max_length=50)),
                ('Email_post', models.EmailField(max_length=50)),
                ('Email_apply', models.EmailField(max_length=50)),
                ('Apply_date', models.DateField(default=django.utils.timezone.now)),
                ('Deadline', models.DateField()),
                ('resume', models.FileField(upload_to=cdacalumini.models.user_directory_path, validators=[cdacalumini.validators.validate_file_extension])),
                ('Salary', models.CharField(blank=True, max_length=20, null=True)),
                ('About_company', models.TextField(blank=True, null=True)),
                ('About_role', models.TextField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=20, null=True)),
                ('Mobile_no', models.CharField(blank=True, max_length=12, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('', 'Role'), ('Intern', 'Intern'), ('Employee', 'Employee'), ('Trainee', 'Trainee')], max_length=50)),
                ('Technology', models.CharField(choices=[('', 'Technology'), ('Python', 'Python'), ('Big data', 'Big data'), ('Java', 'java'), ('Data science', 'Data science'), ('IOT', 'IOT'), ('Security', 'Security')], max_length=50)),
                ('Batch', models.CharField(choices=[('', 'Batch'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019')], max_length=50)),
                ('Profile_photo', models.ImageField(upload_to='media/')),
                ('Gender', models.CharField(choices=[('', 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('Mobile_no', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('College', models.CharField(max_length=200)),
                ('Degree', models.CharField(choices=[('', 'Degree'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('B.Ca', 'B.CA'), ('M.Ca', 'M.Ca')], max_length=50)),
                ('Department', models.CharField(max_length=200)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=50)),
                ('Job_title', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=20)),
                ('Deadline', models.DateField()),
                ('Salary', models.CharField(max_length=20)),
                ('About_company', models.TextField()),
                ('About_role', models.TextField()),
                ('Your_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Currentdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(blank=True, max_length=50)),
                ('from_user', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('friends', models.ManyToManyField(blank=True, to='cdacalumini.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
