# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='media/')),
                ('pic2', models.ImageField(upload_to='media/')),
                ('pic3', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.IntegerField(max_length=12)),
                ('phone2', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_pic', models.ImageField(upload_to='media/')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpic', models.ImageField(upload_to='media/')),
                ('tmessage', models.TextField()),
                ('tname', models.CharField(max_length=50)),
                ('tsign', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
