# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0002_carousel_con_dir_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('duration', models.CharField(max_length=2)),
                ('link', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
