# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0004_auto_20190720_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Sjob',
        ),
    ]
