# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0005_auto_20190720_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('', 'level'), ('beginner', 'beginner'), ('Intermediate', 'Intermdeiate'), ('Advanced', 'Advanced')], default='beginner', max_length=100),
        ),
    ]
