# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0006_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Role',
            field=models.CharField(choices=[('', 'Role'), ('Intern', 'Intern'), ('Trainee', 'Trainee')], max_length=50),
        ),
    ]
