# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0008_auto_20190722_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sjob',
            name='location',
        ),
        migrations.RemoveField(
            model_name='training',
            name='location',
        ),
    ]
