# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0009_auto_20190722_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='training',
            name='duration',
        ),
        migrations.AddField(
            model_name='intern',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 22, 16, 50, 42, 201493, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='intern',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 22, 16, 50, 42, 201493, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 22, 16, 50, 42, 201493, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 22, 16, 50, 42, 201493, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='training',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 22, 16, 50, 42, 201493, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='training',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 22, 16, 50, 42, 201493, tzinfo=utc)),
        ),
    ]
