# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0010_auto_20190722_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='Technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='cdacalumini.Technology'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 0, 12, 663123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='intern',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 0, 12, 663123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 0, 12, 663123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 0, 12, 663123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 0, 12, 667116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 0, 12, 667116, tzinfo=utc)),
        ),
    ]
