# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 05:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0011_auto_20190723_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_user', to='cdacalumini.Technology'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 2, 44, 207160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='intern',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 2, 44, 207160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 2, 44, 207160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 2, 44, 207160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 2, 44, 207160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 2, 44, 207160, tzinfo=utc)),
        ),
    ]
