# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 05:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0012_auto_20190723_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Technology',
            field=models.CharField(choices=[('', 'Technology'), ('Python', 'Python'), ('Big data', 'Big data'), ('Java', 'java'), ('Data science', 'Data science'), ('IOT', 'IOT'), ('Security', 'Security')], max_length=50),
        ),
        migrations.AlterField(
            model_name='intern',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 10, 6, 638197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='intern',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 10, 6, 638197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 10, 6, 638197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 10, 6, 638197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 10, 6, 638197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 5, 10, 6, 638197, tzinfo=utc)),
        ),
    ]
