# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0013_auto_20190723_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='intern',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 10, 36, 25, 702296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='intern',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 10, 36, 25, 702296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 10, 36, 25, 702296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 10, 36, 25, 702296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='endd',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 10, 36, 25, 702296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='startd',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 10, 36, 25, 702296, tzinfo=utc)),
        ),
    ]
