# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-06 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cdacalumini', '0014_auto_20190724_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con',
            name='phone1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='con',
            name='phone2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='intern',
            name='endd',
            field=models.DateField(default=datetime.datetime(2020, 1, 6, 8, 48, 49, 356135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='intern',
            name='startd',
            field=models.DateField(default=datetime.datetime(2020, 1, 6, 8, 48, 49, 356135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='endd',
            field=models.DateField(default=datetime.datetime(2020, 1, 6, 8, 48, 49, 356135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startd',
            field=models.DateField(default=datetime.datetime(2020, 1, 6, 8, 48, 49, 356135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='endd',
            field=models.DateField(default=datetime.datetime(2020, 1, 6, 8, 48, 49, 356135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='startd',
            field=models.DateField(default=datetime.datetime(2020, 1, 6, 8, 48, 49, 356135, tzinfo=utc)),
        ),
    ]
